#!/bin/bash

# update submodules
git submodule update --init --recursive

./tasks/clear-logs

# generate template based files
php tasks/scc/scc.php config/custom_constants.txt

# start node server & log output & reload when server files changes
forever -d -v stop app/server/app.js
forever -a -v -d -o log/app.log -e log/app-err.log start -w app/server/app.js

# start watcher to reload browser when files change
grunt watch &> /dev/null &

# show logs
tail -f log/app.log -f log/app-err.log &

