#!/bin/bash

# stop server
forever -d -v stop app/server/app.js &> /dev/null

# kill watchers
ps aux | grep "./tasks/watch-and-reload" |  grep -v grep | awk '{print $2}' | xargs kill -9

# kill tails
ps aux | grep "tail -f log/app.log" | grep -v grep | awk '{print $2}' | xargs kill -9

exit 0